[package]
name = "service"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# TODO: this dependency is only needed for the canonical ABI exports
# potentially we could generate them as an additional dependency instead
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen"}

[package.metadata.component.dependencies]
cache = { version = "0.1.0", path = "cache.wit" }
origin = { version = "0.1.0", path = "backend.wit" }
backend = { version = "0.1.0", path = "backend.wit", export = true }
